### ISSUE TITLE
Java 8 support

### ISSUE THREAD

**Issue by Jeffset** [tschuchortdev/kotlin-compile-testing#214]
When using jdk8, I get the following error:
```
java.lang.IllegalAccessError: tried to access class com.sun.tools.javac.util.Log$2 from class com.sun.tools.javac.util.Log
	at com.sun.tools.javac.util.Log.getWriter(Log.java:372)
	at com.sun.tools.javac.main.Main.bugMessage(Main.java:588)
	at com.sun.tools.javac.main.Main.compile(Main.java:568)
	at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
	at com.tschuchort.compiletesting.KotlinCompilation.compileJava(KotlinCompilation.kt:578)
	at com.tschuchort.compiletesting.KotlinCompilation.compile(KotlinCompilation.kt:653)
	[... redacted]
```
Is there something wrong with my environment or this framework is broken under Java 8?

**Comment by Jeffset** [comment]
Oh, no, started using jdk11 long ago. I think we can reopen this if anybody else reproduces the issue
