### ISSUE TITLE
Fails on Kotlin 1.7.0-RC

### ISSUE THREAD

**Issue by drewhamilton** [tschuchortdev/kotlin-compile-testing#268]
When bumping my compiler plugin to Kotlin 1.7.0-RC, tests fail with a NoSuchMethodError:

```
'void org.jetbrains.kotlin.cli.common.arguments.ParseCommandLineArgumentsKt.parseCommandLineArguments(java.util.List, org.jetbrains.kotlin.cli.common.arguments.CommonToolArguments)'
java.lang.NoSuchMethodError: 'void org.jetbrains.kotlin.cli.common.arguments.ParseCommandLineArgumentsKt.parseCommandLineArguments(java.util.List, org.jetbrains.kotlin.cli.common.arguments.CommonToolArguments)'
	at com.tschuchort.compiletesting.AbstractKotlinCompilation.commonArguments(AbstractKotlinCompilation.kt:157)
	at com.tschuchort.compiletesting.KotlinCompilation.commonK2JVMArgs(KotlinCompilation.kt:300)
	at com.tschuchort.compiletesting.KotlinCompilation.compileJvmKotlin(KotlinCompilation.kt:488)
	at com.tschuchort.compiletesting.KotlinCompilation.compile(KotlinCompilation.kt:664)
```

At a glance it looks like a third default argument was added to `parseCommandLineArguments`.

**Comment by tschuchortdev** [comment]
Can you try with the latest snapshot version? I just upgraded KSP and Kotlin to 1.7.0-RC on master.
