### ISSUE TITLE
INTERNAL_ERROR - Fatal Error: Unable to find package java.lang in classpath or bootclasspath

### ISSUE THREAD

**Issue by ValdZX** [tschuchortdev/kotlin-compile-testing#3]
plugins {
    kotlin("jvm") version "1.3.41"
    kotlin("kapt") version "1.3.41"
}

allprojects {
    repositories {
        ...
        maven(url = "https://jitpack.io")
    }
}

dependencies {
    kapt("com.google.auto.service:auto-service:1.0-rc6")
    implementation(kotlin("stdlib-jdk8"))
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.1.0")
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:5.1.0")
    testImplementation("com.github.tschuchortdev:kotlin-compile-testing:1.1.2")
    testImplementation("io.kotlintest:kotlintest-runner-junit5:3.4.0")
    testImplementation(files(Jvm.current().toolsJar))
}

exception: java.lang.IllegalStateException: failed to analyze: com.sun.tools.javac.util.FatalError: Fatal Error: Unable to find package **java.lang** in classpath or bootclasspath
	at org.jetbrains.kotlin.analyzer.AnalysisResult.throwIfError(AnalysisResult.kt:56)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.analyzeAndGenerate(KotlinToJVMBytecodeCompiler.kt:361)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileBunchOfSources(KotlinToJVMBytecodeCompiler.kt:258)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:205)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:57)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:96)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:52)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:93)
	at com.tschuchort.compiletesting.KotlinCompilation.stubsAndApt(_**KotlinCompilation.kt:493**_)
	at com.tschuchort.compiletesting.KotlinCompilation.compile(_**KotlinCompilation.kt:674**_)
	...

**Comment by tschuchortdev** [comment]
What options are you calling `KotlinCompilation` with and what JDK are you using? 

It looks to me like there is no JDK on the classpath of the compilation. This can happen if `KotlinCompilation.jdkHome = null` and `KotlinCompilation.inheritClassPath = false`. So if you set `inheritClassPath = true`, hopefully it should work.

**Comment by ValdZX** [comment]
Truble fixet before defining jdkHome
```
        val result = KotlinCompilation().apply {
            jdkHome = File("C:\\Program Files\\Java\\jdk1.8.0_211")
            ...
        }.compile()
```
But why dont used context jdk or JAVA_HOME by default?

**Comment by ValdZX** [comment]
Mayby set File(System.getProperty("java.home")).parentFile for default jdkHome?

**Comment by tschuchortdev** [comment]
If `inheritClassPath=true` is used then there is already a JDK in the classpath. Perhaps it would be better to only initialize it as null if `inheritClassPath` is actually `true`, or at least show a warning to prevent people from running into this issue.
