### ISSUE TITLE
NoClassDefFoundError on Java 11

### ISSUE THREAD

**Issue by breandan** [tschuchortdev/kotlin-compile-testing#300]
I recently tried upgrading from JVM version `1.8` to `11` by setting `kotlinOptions.jvmTarget = "11"`, however I encountered the following error when using this library:

```
    java.lang.NoClassDefFoundError: org/jetbrains/kotlin/cli/jvm/plugins/ServiceLoaderLite
        at com.tschuchort.compiletesting.AbstractKotlinCompilation.getResourcesPath(AbstractKotlinCompilation.kt:219)
        at com.tschuchort.compiletesting.AbstractKotlinCompilation.compileKotlin(AbstractKotlinCompilation.kt:194)
        at com.tschuchort.compiletesting.KotlinCompilation.compileJvmKotlin(KotlinCompilation.kt:488)
        at com.tschuchort.compiletesting.KotlinCompilation.compile(KotlinCompilation.kt:664)
...

        Caused by:
        java.lang.ClassNotFoundException: org.jetbrains.kotlin.cli.jvm.plugins.ServiceLoaderLite
            at com.tschuchort.compiletesting.AbstractKotlinCompilation.getResourcesPath(AbstractKotlinCompilation.kt:219)
            ... 5 more
```

**Comment by tschuchortdev** [comment]
Please send the output of `gradle dependencies` task and gradle files for relevant modules. I tried it just now with 
```
tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).all {
    kotlinOptions {
        jvmTarget = "11"
    }
}
```
and a JDK 11 and it worked fine.
