### ISSUE TITLE
Incompatible with 1.4.0

### ISSUE THREAD

**Issue by ZacSweers** [tschuchortdev/kotlin-compile-testing#51]
```
logging: Created temporary working directory at /tmp/Kotlin-Compilation5855002191926930255
logging: Searched host classpaths for kotlin-stdlib.jar and found no match
logging: Searched host classpaths for kotlin-stdlib-common.jar and found no match
logging: Searched host classpaths for kotlin-stdlib-jdk*.jar and found no match
logging: Searched host classpaths for kotlin-reflect.jar and found no match
logging: Searched host classpaths for kotlin-script-runtime.jar and found no match
logging: Inheriting classpaths:  /home/ubuntu/actions-runner/_work/_tool/jdk/8.0.252/x64/jre/lib/rt.jar:/home/ubuntu/actions-runner/_work/_tool/jdk/8.0.252/x64/jre/lib/ext/sunpkcs11.jar:/home/ubuntu/actions-runner/_work/_tool/jdk/8.0.252/x64/jre/lib/ext/sunjce_provider.jar:/home/ubuntu/actions-runner/_work/_tool/jdk/8.0.252/x64/jre/lib/ext/dnsns.jar:/home/ubuntu/actions-runner/_work/_tool/jdk/8.0.252/x64/jre/lib/ext/sunec.jar:/home/ubuntu/actions-runner/_work/_tool/jdk/8.0.252/x64/jre/lib/ext/localedata.jar:/home/ubuntu/actions-runner/_work/_tool/jdk/8.0.252/x64/jre/lib/ext/jaccess.jar:/home/ubuntu/actions-runner/_work/_tool/jdk/8.0.252/x64/jre/lib/ext/openjsse.jar:/home/ubuntu/actions-runner/_work/_tool/jdk/8.0.252/x64/jre/lib/ext/nashorn.jar:/home/ubuntu/actions-runner/_work/_tool/jdk/8.0.252/x64/jre/lib/ext/cldrdata.jar:/home/ubuntu/actions-runner/_work/_tool/jdk/8.0.252/x64/jre/lib/ext/zipfs.jar:/home/ubuntu/.gradle/caches/6.5.1/workerMain/gradle-worker.jar:/home/ubuntu/actions-runner/_work/slack-android-ng/slack-android-ng/minimized-feature-flag-compiler/build/tmp/expandedArchives/org.jacoco.agent-0.8.4.jar_982888894296538c98d7324f3ca78d8f/jacocoagent.jar:/home/ubuntu/actions-runner/_work/slack-android-ng/slack-android-ng/minimized-feature-flag-compiler/build/classes/kotlin/test:/home/ubuntu/actions-runner/_work/slack-android-ng/slack-android-ng/minimized-feature-flag-compiler/build/tmp/kapt3/classes/test:/home/ubuntu/actions-runner/_work/slack-android-ng/slack-android-ng/minimized-feature-flag-compiler/build/classes/kotlin/main:/home/ubuntu/actions-runner/_work/slack-android-ng/slack-android-ng/minimized-feature-flag-compiler/build/tmp/kapt3/classes/main:/home/ubuntu/actions-runner/_work/_tool/jdk/8.0.252/x64/lib/tools.jar:/home/ubuntu/actions-runner/_work/slack-android-ng/slack-android-ng/feature-flag-library/build/libs/feature-flag-library.jar:/home/ubuntu/actions-runner/_work/slack-android-ng/slack-android-ng/minimized-feature-flag-library/build/libs/minimized-feature-flag-library.jar:/home/ubuntu/.gradle/caches/modules-2/files-2.1/com.github.tschuchortdev/kotlin-compile-testing/1.2.9/809d83c453c3eaeae50a5de110d921ac54dae314/kotlin-compile-testing-1.2.9.jar:/home/ubuntu/.gradle/caches/modules-2/files-2.1/com.squareup/kotlinpoet/1.6.0/6ce4c42da0daf2ba11a4180d33360e8c049ef5b8/kotlinpoet-1.6.0.jar:/home/ubuntu/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk8/1.4-M3/14dcd66c9362b834a2491028b87db75a88fdbac0/kotlin-stdlib-jdk8-1.4-M3.jar:/home/ubuntu/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-compiler-embeddable/1.4-M3/67dfdd73f5fdc275f857d9aab325bd205003fdd6/kotlin-compiler-embeddable-1.4-M3.jar:/home/ubuntu/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-reflect/1.4-M3/a00dc5d9fe4c80832afd33c61310e9ad69d7af16/kotlin-reflect-1.4-M3.jar:/home/ubuntu/.gradle/caches/modules-2/files-2.1/com.squareup.okio/okio/2.6.0/f06923d428f3c8e6f571043ec29a45d0cd9d2bf/okio-jvm-2.6.0.jar:/home/ubuntu/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk7/1.4-M3/3d648cd3e9ac8cea2febc25dccd42fa2667fac75/kotlin-stdlib-jdk7-1.4-M3.jar:/home/ubuntu/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.4-M3/d434fee0dcf45da74fbb897d7db3e24993e6be2c/kotlin-stdlib-1.4-M3.jar:/home/ubuntu/.gradle/caches/modules-2/files-2.1/com.google.dagger/dagger/2.28.1/8812e1a1aac785d4aba387857f29bee887722fb0/dagger-2.28.1.jar:/home/ubuntu/.gradle/caches/modules-2/files-2.1/javax.inject/javax.inject/1/6975da39a7040257bd51d21a231b76c915872d38/javax.inject-1.jar:/home/ubuntu/.gradle/caches/modules-2/files-2.1/com.google.truth/truth/1.0.1/361459309085bd9441cb97b62f160e8b353a93c0/truth-1.0.1.jar:/home/ubuntu/.gradle/caches/modules-2/files-2.1/junit/junit/4.13/e49ccba652b735c93bd6e6f59760d8254cf597dd/junit-4.13.jar:/home/ubuntu/.gradle/caches/modules-2/files-2.1/com.google.guava/guava/28.1-android/c2526f8fad32a65a6d7032dd8e9524eb276b108b/guava-28.1-android.jar:/home/ubuntu/.gradle/caches/modules-2/files-2.1/org.checkerframework/checker-compat-qual/2.5.5/435dc33e3019c9f019e15f01aa111de9d6b2b79c/checker-compat-qual-2.5.5.jar:/home/ubuntu/.gradle/caches/modules-2/files-2.1/org.jetbrains/annotations/13.0/919f0dfe192fb4e063e7dacadee7f8bb9a2672a9/annotations-13.0.jar:/home/ubuntu/.gradle/caches/modules-2/files-2.1/com.google.code.findbugs/jsr305/3.0.2/25ea2e8b0c338a877313bd4672d3fe056ea78f0d/jsr305-3.0.2.jar:/home/ubuntu/.gradle/caches/modules-2/files-2.1/com.google.auto.value/auto-value-annotations/1.7.3/59ce5ee6aea918f674229f1147da95fdf7f31ce6/auto-value-annotations-1.7.3.jar:/home/ubuntu/.gradle/caches/modules-2/files-2.1/com.google.errorprone/error_prone_annotations/2.4.0/32ecccc595e4e4d813a80ee9e3ab5813d65874eb/error_prone_annotations-2.4.0.jar:/home/ubuntu/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-common/1.4-M3/9f0db946b8160929e99f26df2ae3e65356978141/kotlin-stdlib-common-1.4-M3.jar:/home/ubuntu/.gradle/caches/modules-2/files-2.1/org.hamcrest/hamcrest/2.2/1820c0968dba3a11a1b30669bb1f01978a91dedc/hamcrest-2.2.jar:/home/ubuntu/.gradle/caches/modules-2/files-2.1/com.googlecode.java-diff-utils/diffutils/1.3.0/7e060dd5b19431e6d198e91ff670644372f60fbd/diffutils-1.3.0.jar:/home/ubuntu/.gradle/caches/modules-2/files-2.1/io.github.classgraph/classgraph/4.8.86/4dd4f839a1c7674e6906023cfb57d86954fb86df/classgraph-4.8.86.jar:/home/ubuntu/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-annotation-processing-embeddable/1.3.72/2d9972c8c99a775accfa38196ee47f3ac29be09/kotlin-annotation-processing-embeddable-1.3.72.jar:/home/ubuntu/.gradle/caches/modules-2/files-2.1/com.google.guava/failureaccess/1.0.1/1dcf1de382a0bf95a3d8b0849546c88bac1292c9/failureaccess-1.0.1.jar:/home/ubuntu/.gradle/caches/modules-2/files-2.1/com.google.guava/listenablefuture/9999.0-empty-to-avoid-conflict-with-guava/b421526c5f297295adef1c886e5246c39d4ac629/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar:/home/ubuntu/.gradle/caches/modules-2/files-2.1/com.google.j2objc/j2objc-annotations/1.3/ba035118bc8bac37d7eff77700720999acd9986d/j2objc-annotations-1.3.jar:/home/ubuntu/.gradle/caches/modules-2/files-2.1/org.codehaus.mojo/animal-sniffer-annotations/1.18/f7aa683ea79dc6681ee9fb95756c999acbb62f5d/animal-sniffer-annotations-1.18.jar:/home/ubuntu/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-script-runtime/1.4-M3/f41bf9bc6b35b83040eedcdd482651d2f843e12f/kotlin-script-runtime-1.4-M3.jar:/home/ubuntu/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-daemon-embeddable/1.4-M3/b214990d2189e8eb24f79b4564f834023f8f7192/kotlin-daemon-embeddable-1.4-M3.jar:/home/ubuntu/.gradle/caches/modules-2/files-2.1/org.jetbrains.intellij.deps/trove4j/1.0.20181211/216c2e14b070f334479d800987affe4054cd563f/trove4j-1.0.20181211.jar:/home/ubuntu/.gradle/wrapper/dists/gradle-6.5.1-all/cdund22i8guosqylfo49op4dv/gradle-6.5.1/lib/gradle-core-api-6.5.1.jar:/home/ubuntu/.gradle/wrapper/dists/gradle-6.5.1-all/cdund22i8guosqylfo49op4dv/gradle-6.5.1/lib/gradle-worker-processes-6.5.1.jar:/home/ubuntu/.gradle/wrapper/dists/gradle-6.5.1-all/cdund22i8guosqylfo49op4dv/gradle-6.5.1/lib/gradle-core-6.5.1.jar:/home/ubuntu/.gradle/wrapper/dists/gradle-6.5.1-all/cdund22i8guosqylfo49op4dv/gradle-6.5.1/lib/gradle-logging-6.5.1.jar:/home/ubuntu/.gradle/wrapper/dists/gradle-6.5.1-all/cdund22i8guosqylfo49op4dv/gradle-6.5.1/lib/gradle-messaging-6.5.1.jar:/home/ubuntu/.gradle/wrapper/dists/gradle-6.5.1-all/cdund22i8guosqylfo49op4dv/gradle-6.5.1/lib/gradle-files-6.5.1.jar:/home/ubuntu/.gradle/wrapper/dists/gradle-6.5.1-all/cdund22i8guosqylfo49op4dv/gradle-6.5.1/lib/gradle-hashing-6.5.1.jar:/home/ubuntu/.gradle/wrapper/dists/gradle-6.5.1-all/cdund22i8guosqylfo49op4dv/gradle-6.5.1/lib/gradle-base-services-6.5.1.jar:/home/ubuntu/.gradle/wrapper/dists/gradle-6.5.1-all/cdund22i8guosqylfo49op4dv/gradle-6.5.1/lib/gradle-cli-6.5.1.jar:/home/ubuntu/.gradle/wrapper/dists/gradle-6.5.1-all/cdund22i8guosqylfo49op4dv/gradle-6.5.1/lib/gradle-native-6.5.1.jar:/home/ubuntu/.gradle/wrapper/dists/gradle-6.5.1-all/cdund22i8guosqylfo49op4dv/gradle-6.5.1/lib/plugins/gradle-testing-base-6.5.1.jar:/home/ubuntu/.gradle/wrapper/dists/gradle-6.5.1-all/cdund22i8guosqylfo49op4dv/gradle-6.5.1/lib/plugins/gradle-testing-jvm-6.5.1.jar:/home/ubuntu/.gradle/wrapper/dists/gradle-6.5.1-all/cdund22i8guosqylfo49op4dv/gradle-6.5.1/lib/plugins/gradle-testing-junit-platform-6.5.1.jar:/home/ubuntu/.gradle/wrapper/dists/gradle-6.5.1-all/cdund22i8guosqylfo49op4dv/gradle-6.5.1/lib/gradle-process-services-6.5.1.jar:/home/ubuntu/.gradle/wrapper/dists/gradle-6.5.1-all/cdund22i8guosqylfo49op4dv/gradle-6.5.1/lib/slf4j-api-1.7.28.jar:/home/ubuntu/.gradle/wrapper/dists/gradle-6.5.1-all/cdund22i8guosqylfo49op4dv/gradle-6.5.1/lib/jul-to-slf4j-1.7.28.jar:/home/ubuntu/.gradle/wrapper/dists/gradle-6.5.1-all/cdund22i8guosqylfo49op4dv/gradle-6.5.1/lib/native-platform-0.22-milestone-3.jar:/home/ubuntu/.gradle/wrapper/dists/gradle-6.5.1-all/cdund22i8guosqylfo49op4dv/gradle-6.5.1/lib/kryo-2.24.0.jar:/home/ubuntu/.gradle/wrapper/dists/gradle-6.5.1-all/cdund22i8guosqylfo49op4dv/gradle-6.5.1/lib/commons-lang-2.6.jar:/home/ubuntu/.gradle/wrapper/dists/gradle-6.5.1-all/cdund22i8guosqylfo49op4dv/gradle-6.5.1/lib/plugins/junit-4.13.jar
v: Using Kotlin home directory <no_path>
v: Using JDK home directory /home/ubuntu/actions-runner/_work/_tool/jdk/8.0.252/x64
v: Scripting plugin will not be loaded: not all required jars are present in the classpath (missing files: [./kotlin-scripting-compiler.jar, ./kotlin-scripting-compiler-impl.jar, ./kotlinx-coroutines-core.jar, ./kotlin-scripting-common.jar, ./kotlin-scripting-jvm.jar, ./kotlin-scripting-js.jar, ./js.engines.jar])
v: Configuring the compilation environment
e: java.lang.NoSuchMethodError: org.jetbrains.kotlin.cli.common.messages.MessageCollector$DefaultImpls.report$default(Lorg/jetbrains/kotlin/cli/common/messages/MessageCollector;Lorg/jetbrains/kotlin/cli/common/messages/CompilerMessageSeverity;Ljava/lang/String;Lorg/jetbrains/kotlin/cli/common/messages/CompilerMessageLocation;ILjava/lang/Object;)V
	at org.jetbrains.kotlin.kapt3.util.MessageCollectorBackedKaptLogger.info(MessageCollectorBackedKaptLogger.kt:38)
	at com.tschuchort.compiletesting.KaptComponentRegistrar.registerProjectComponents(KaptComponentRegistrar.kt:88)
	at com.tschuchort.compiletesting.MainComponentRegistrar.registerProjectComponents(MainComponentRegistrar.kt:44)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$Companion.registerExtensionsFromPlugins$cli(KotlinCoreEnvironment.kt:563)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$ProjectEnvironment.registerExtensionsFromPlugins(KotlinCoreEnvironment.kt:129)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.<init>(KotlinCoreEnvironment.kt:169)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.<init>(KotlinCoreEnvironment.kt:109)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$Companion.createForProduction(KotlinCoreEnvironment.kt:421)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.createCoreEnvironment(K2JVMCompiler.kt:220)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:151)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:51)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:86)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:44)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:98)
	at com.tschuchort.compiletesting.KotlinCompilation.stubsAndApt(KotlinCompilation.kt:579)
	at com.tschuchort.compiletesting.KotlinCompilation.compile(KotlinCompilation.kt:801)
	at slack.features.annotation.codegen.MinimizedFeatureFlagProcessorTest.testProcessFailWithNoServerFeatureFlag(MinimizedFeatureFlagProcessorTest.kt:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:119)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:414)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by tschuchortdev** [comment]
1.4-M3 is a pre-release and unfortunately I can not support multiple Kotlin versions at the same time because the maintainance burden of back-porting changes would be too great. You can try using the KSP build which is at 1.4-M2 I think or of course you can fork the project and update the version yourself.

**Comment by ZacSweers** [comment]
I know, just filing for your awareness

**Comment by vinaygaba** [comment]
I am seeing a different error after I upgraded it to a custom version of 1.4-M3. Wondering if its the same problem or there is actually a way around it

```
e: Incompatible classes were found in dependencies. Remove them from the classpath or use '-Xskip-metadata-version-check' to suppress errors
e: /var/folders/rp/h636r1d97wq_gs5nnrzgbv2r0000gn/T/Kotlin-Compilation4456701634743116043/kapt/sources/com/example/showkase/Example.kt: (4, 46): Class 'com.example.DemoClass is compiled by a pre-release version of Kotlin and cannot be loaded by this version of the compiler
```

@ZacSweers @tschuchortdev

**Comment by tschuchortdev** [comment]
@vinaygaba Is DemoClass a class that was compiled normally in your project and you are inheriting the classpath? If so then my hypothesis is that your system compiler is at 1.4-M3 and the Kotlin-Compile-Testing embedded compiler dependency is at an earlier version that doesn't understand the newer metadata of DemoClass while trying to compile Example.kt which references DemoClass. Or perhaps the other way around.

**Comment by vinaygaba** [comment]
Yes the DemoClass is a part of my main module and I am inheriting the classpath using this logic

```
static def getRuntimeJar() {
    try {
        final File javaBase = new File(System.getProperty("java.home")).getCanonicalFile()
        File runtimeJar = new File(javaBase, "lib/rt.jar")
        if (runtimeJar.exists()) {
            return runtimeJar
        }
        runtimeJar = new File(javaBase, "jre/lib/rt.jar")
        return runtimeJar.exists() ? runtimeJar : null
    } catch (IOException e) {
        throw new RuntimeException(e)
    }
}
```

In that case, is the only solution to wait until 1.4 is stable and the embedded compiler is also upgraded for this library? @tschuchortdev

**Comment by tschuchortdev** [comment]
I'm afraid your only options are to wait for a new release, which will either happen when the KSP-specific artifact is updated to 1.4-M3 (less likely) or when 1.4 is stable and the main artifact is updated (much more likely but will take longer) or you can make a fork and update it yourself. You can also try to just [overwrite](https://stackoverflow.com/questions/30728533/gradle-override-transitive-dependency-by-version-classifier) the kotlin-compiler-embeddable transitive dependency with a newer one for 1.4-M3 , but you will probably run into the same problem as @ZacSweers, which can only be fixed by forking the project and changing the `KaptComponentRegistrar` to no longer use the `org.jetbrains.kotlin.cli.common.messages.MessageCollector$DefaultImpls.report$default(Lorg/jetbrains/kotlin/cli/common/messages/MessageCollector;Lorg/jetbrains/kotlin/cli/common/messages/CompilerMessageSeverity;Ljava/lang/String;Lorg/jetbrains/kotlin/cli/common/messages/CompilerMessageLocation;ILjava/lang/Object;)V` method which was removed in the new compiler version.

**Comment by vinaygaba** [comment]
@tschuchortdev Thank you so much for giving me more direction, I really appreciate it!

**Comment by rachelcarmena** [comment]
I had the same problems because Kotlin 1.4.x is not backward-compatible with 1.3.x and I created a custom version for this library until the release is available :raised_hands:

**Comment by vinaygaba** [comment]
@rachelcarmena Are you already hosting it somewhere? I'd love to use it!

**Comment by rachelcarmena** [comment]
> @rachelcarmena Are you already hosting it somewhere? I'd love to use it!

Of course!! 

Some things to keep in mind:

* Besides changing the Kotlin version and adding the EAP repository, I updated Gradle from 4.3.10 to 5.6.4 because it was not possible to apply the Kotlin plugin.
* Maybe it's necessary to make more changes because of: https://kotlinlang.org/docs/reference/compatibility-guide-14.html. However, it works for our current use.
* It fails for `openjdk14`.

Data for using the library with Kotlin `1.4.0-rc`:
* Dependency:  `"com.github.arrow-kt:kotlin-compile-testing:1.2.8.2"` because it's based on 1.2.8 and 1.2.8.1 was a test for 1.4-M3. I didn't use latest release (1.2.9) because it raised some errors and the new features for that version weren't needed.
* Repository: `maven { url "https://jitpack.io" }`

It comes from a forked repository and a tag. Jitpack magic makes the rest of things :wink: 

Small note for @tschuchortdev : I realized that Kotlin Gradle plugin is applied twice (following both the plugin DSL and the legacy plugin application). So one of them could be removed: https://plugins.gradle.org/plugin/org.jetbrains.kotlin.jvm

And kudos again for @tschuchortdev for such amazing and useful library :raised_hands:

**Comment by tschuchortdev** [comment]
@rachelcarmena I'm looking forward to your PR. Was it not necessary to change anything in the `KaptComponentRegistrar`? I thought that's where the most work would have to be done to update to 1.4. Or did you simply remove it for use in Arrow which doesn't need Kapt?

**Comment by rachelcarmena** [comment]
> @rachelcarmena I'm looking forward to your PR. Was it not necessary to change anything in the `KaptComponentRegistrar`? I thought that's where the most work would have to be done to update to 1.4. Or did you simply remove it for use in Arrow which doesn't need Kapt?

Thanks for the point @tschuchortdev !! It's not used on Meta and I'm going to remove the plugin to avoid misunderstandings. Thanks!!

**Comment by vinaygaba** [comment]
@rachelcarmena Thank you so much for creating this fork! I'm going to give it a shot and let you know how it goes!

**Comment by vRallev** [comment]
I'm curious what the status of this ticket now that 1.4 is released?

**Comment by vinaygaba** [comment]
@vRallev In my experience, this library worked with `1.4.0` but did not work with `1.4-M3`. I'm not sure why that is the case though.

**Comment by tschuchortdev** [comment]
Now that 1.4 is released I'm working on removing the complicated included build for the ksp artifact and moving it to a regular submodule but I'm still having some trouble with the Gradle scripts. Hopefully I will release a new version for 1.4 tomorrow or the day after. Meanwhile you can just use an older version and override the transitive dependency on `kotlin-compiler-embeddable` with the one for 1.4. Like @vinaygaba said, the breaking change in the compiler's logging API seems to have been reverted and now it works fine even with the old KCT code.

**Comment by ZacSweers** [comment]
Ksp is not in 1.4 and still requires use of its own fork for now. It's possible that once it bases on to 1.4 it may not need its own fork to run, but I doubt it

**Comment by ZacSweers** [comment]
A lot of projects are waiting on this support. @tschuchortdev looks like #58 resolved this. Anything else you want help with for a release?

**Comment by tschuchortdev** [comment]
I have released version 1.2.10 which should work with Kotlin 1.4.0 and automated the release process a bit more. The artifact in the repository seems to be a *.module file now and no longer *.jar. I hope that won't be a problem. It worked when I tested it, even with JDK 8.

**Comment by rachelcarmena** [comment]
Thanks @tschuchortdev :tada: The `.module` is a new file from `maven-publish` plugin. This text is included in `.pom` file about it:

```
  <!-- This module was also published with a richer model, Gradle metadata,  -->
  <!-- which should be used instead. Do not delete the following line which  -->
  <!-- is to indicate to Gradle or any Gradle module metadata file consumer  -->
  <!-- that they should prefer consuming it instead. -->
  <!-- do_not_remove: published-with-gradle-metadata -->
```

I found the `.jar` file as well: https://repo1.maven.org/maven2/com/github/tschuchortdev/kotlin-compile-testing/1.2.10/

Everything is ok :raised_hands: Thanks!!

**Comment by tschuchortdev** [comment]
@rachelcarmena Huh, when I search on oss.sonatype.org it only shows the sources jar, javadoc jar and module file. Do you happen to know why?

![image](https://user-images.githubusercontent.com/7273344/91473126-b9e9c600-e898-11ea-908d-2ddb4d2fac7f.png)

**Comment by rachelcarmena** [comment]
> @rachelcarmena Huh, when I search on oss.sonatype.org it only shows the sources jar, javadoc jar and module file. Do you happen to know why?
> 
> ![image](https://user-images.githubusercontent.com/7273344/91473126-b9e9c600-e898-11ea-908d-2ddb4d2fac7f.png)

OMG! It seems a failure on the GUI because it's included in the list of contents: https://oss.sonatype.org/service/local/repositories/releases/content/com/github/tschuchortdev/kotlin-compile-testing/1.2.10/

And the included link works: https://oss.sonatype.org/service/local/repositories/releases/content/com/github/tschuchortdev/kotlin-compile-testing/1.2.10/kotlin-compile-testing-1.2.10.jar 

Maybe it's interesting to report the issue :+1:
